# Generated by Django 5.2.14 on 2026-06-03 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_create_default_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalrecord',
            name='bleeding_disorders',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='dental_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='pregnancy',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='surgeries',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='systemic_diseases',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PatientAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='patient_attachments/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_patient_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo do paciente',
                'verbose_name_plural': 'Anexos dos pacientes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
