from django.urls import path

from .views import (
    UserLoginView,
    UserLogoutView,
    agenda_view,
    appointment_cancel_view,
    appointment_create_view,
    appointment_delete_view,
    appointment_edit_view,
    appointment_list_view,
    clinical_history_create_view,
    clinical_history_update_view,
    dashboard_view,
    dental_record_detail_view,
    dental_record_pdf_view,
    dental_record_update_view,
    clinical_history_delete_view,
    odontogram_entry_upsert_view,
    odontogram_entry_delete_view,
    patient_create_view,
    patient_delete_view,
    patient_detail_view,
    patient_edit_view,
    patient_list_view,
    patient_attachment_create_view,
    patient_attachment_delete_view,
    register_view,
)

urlpatterns = [
    path("", dashboard_view, name="dashboard"),
    path("auth/login/", UserLoginView.as_view(), name="login"),
    path("auth/logout/", UserLogoutView.as_view(), name="logout"),
    path("auth/register/", register_view, name="register"),
    path("patients/", patient_list_view, name="patients_list"),
    path("patients/new/", patient_create_view, name="patients_create"),
    path("patients/<int:patient_id>/", patient_detail_view, name="patients_detail"),
    path("patients/<int:patient_id>/edit/", patient_edit_view, name="patients_edit"),
    path(
        "patients/<int:patient_id>/delete/",
        patient_delete_view,
        name="patients_delete",
    ),
    path("appointments/", appointment_list_view, name="appointments_list"),
    path("agenda/", agenda_view, name="agenda"),
    path("appointments/new/", appointment_create_view, name="appointments_create"),
    path(
        "appointments/<int:appointment_id>/edit/",
        appointment_edit_view,
        name="appointments_edit",
    ),
    path(
        "appointments/<int:appointment_id>/delete/",
        appointment_delete_view,
        name="appointments_delete",
    ),
    path(
        "appointments/<int:appointment_id>/cancel/",
        appointment_cancel_view,
        name="appointments_cancel",
    ),
    path("patients/<int:patient_id>/record/", dental_record_detail_view, name="patient_record"),
    path(
        "patients/<int:patient_id>/record/update/",
        dental_record_update_view,
        name="patient_record_update",
    ),
    path(
        "patients/<int:patient_id>/record/pdf/",
        dental_record_pdf_view,
        name="patient_record_pdf",
    ),
    path(
        "patients/<int:patient_id>/record/odontogram/",
        odontogram_entry_upsert_view,
        name="patient_record_odontogram",
    ),
    path(
        "patients/<int:patient_id>/record/odontogram/<int:entry_id>/delete/",
        odontogram_entry_delete_view,
        name="patient_record_odontogram_delete",
    ),
    path(
        "patients/<int:patient_id>/record/history/",
        clinical_history_create_view,
        name="patient_record_history",
    ),
    path(
        "patients/<int:patient_id>/record/history/<int:entry_id>/update/",
        clinical_history_update_view,
        name="patient_record_history_update",
    ),
    path(
        "patients/<int:patient_id>/record/history/<int:entry_id>/delete/",
        clinical_history_delete_view,
        name="patient_record_history_delete",
    ),
    path(
        "patients/<int:patient_id>/record/attachments/",
        patient_attachment_create_view,
        name="patient_record_attachment_create",
    ),
    path(
        "patients/<int:patient_id>/record/attachments/<int:attachment_id>/delete/",
        patient_attachment_delete_view,
        name="patient_record_attachment_delete",
    ),
]
